version: "3.7"

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: pwd
      POSTGRES_USER: postgres
      POSTGRES_DB: authdb
    volumes:
      - authdb:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build: .
    environment:
      PORT: 4000
      DBHOST: db
      DBPASSWORD: pwd
      DBUSER: postgres
      DB: authdb
      DBPORT: 5432
    volumes:
      - ./src:/app/src
    ports:
      - "4000:4000"
    depends_on:
      - db

volumes:
  authdb:
